<?php 
include_once('classes/pdo/PdoManager.class.php');
include_once('classes/pdo/PdoArticleManager.class.php');
include_once('classes/pdo/PdoCustomerManager.class.php');
include_once('classes/pdo/PdoDynamic_FieldManager.class.php');
include_once('classes/pdo/PdoDynamic_ValuesManager.class.php');
include_once('classes/pdo/PdoFamilyManager.class.php');
include_once('classes/pdo/PdoLoanManager.class.php');
include_once('classes/pdo/PdoLoan_ArticleManager.class.php');
include_once('classes/pdo/PdoPlaceManager.class.php');
include_once('classes/pdo/PdoStructureManager.class.php');
include_once('classes/pdo/PdoUserManager.class.php');

include_once('classes/model/articlesModel.class.php');
include_once('classes/model/customersModel.class.php');
include_once('classes/model/dynamic_fieldsModel.class.php');
include_once('classes/model/dynamic_valuesModel.class.php');
include_once('classes/model/familiesModel.class.php');
include_once('classes/model/loansModel.class.php');
include_once('classes/model/loans_articlesModel.class.php');
include_once('classes/model/placesModel.class.php');
include_once('classes/model/structuresModel.class.php');
include_once('classes/model/userModel.class.php');
?>
